# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0005_auto_20171110_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
